### ISSUE TITLE
Консоль E2E при запуске сценариев. Присутствуют лишние логи

### ISSUE THREAD

**Issue by M0R0K** [CSSSR/e2e-tools#27]
Фактический результат:

На моей системе при запуске сценариев E2E в терминале частенько проскакивают сообщения о Bluetooth адаптере в консоли. (Использую bluetooth адаптер, подключенный по USB, при его отключении логи все равно остаются) 
http://s.csssr.ru/UUK0K6P5F/2021-04-01-13-17-27-PFI6j.jpg

Ожидаемый результат:

Сообщения такого плана в логах отсутствуют, т.к не относятся непосредственно к сценарию тестов.

**Comment by niktestbom** [comment]
Проблема воспроизводится при запуске тестов локально на Win 10.
