### ISSUE TITLE
Степ проходит успешно в случае клика по несуществующему элементу

### ISSUE THREAD

**Issue by niktestbom** [CSSSR/e2e-tools#31]
Команда `.click()` .
В данной версии если клик происходит по элементу которого нет на странице, то проходит максимально время ожидание, а после шаг проходит как "passed" и тест продолжается дальше(хотя клик выполнен не был).  
В прошлых версия отображалась соответствующая ошибка "NoSuchElementException ..." и сценарий фейлился.

**Comment by xlinur** [comment]
https://nightwatchjs.org/gettingstarted/concepts/#using-test-globals
 
 в nightwatch по-умолчанию теперь ошибка нахождения элемента не вызывает экшепшенов, для изменения установить:
 
 "globals": { "abortOnElementLocateError": true}
