### ISSUE TITLE
При прогоне ошибка Timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by ilchukovaolga** [CSSSR/e2e-tools#38]
Внедряю подготовку тестовых данных через API. Иногда тесткейс отваливается по таймауту

Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

Полагаю, это таймаут от Mocha. Есть возможность его увеличить или как-то по-другому решить проблему? http://s.csssr.ru/UMYJTGU0M/2021-04-21-11-21-59-L278k.jpg

**Comment by Nitive** [comment]
Вот так можно увеличить таймаут

```js
testcase('testcase', () => {
  before(function(browser, done) { // функцию надо объявить именно через function, а не =>, иначе не будет this
    this.timeout(60000)
    ...
  })
```
