### ISSUE TITLE
Текст некоторых ошибок обрезается

### ISSUE THREAD

**Issue by ilchukovaolga** [CSSSR/e2e-tools#40]
Иногда обрезка может быть на названии тест-айди и тогда вообще не понятно, на что именно ругается

http://s.csssr.ru/UMYJTGU0M/2021-04-27-15-15-30-iKR2z.jpg
http://s.csssr.ru/UMYJTGU0M/2021-04-27-15-15-59-m159i.jpg

**Comment by xlinur** [comment]
Обрезка ошибок происходит в модуле транспорта ошибок
node_modules/nightwatch/lib/transport/jsonwire.js

не управляется и не контролируется
