### ISSUE TITLE
Не скрываются псевдоэлементы

### ISSUE THREAD

**Issue by bikmaevakristina** [CSSSR/e2e-tools#48]
Не понятно как с ними взаимодействовать.
Обратиться к ним не получается, вырезать их из скриншот тестов не выходит, даже через див/секцию выше.

Вот этот мальчик сделан как псевдоэлемент http://s.csssr.ru/U2RS0JM28/20210528192252.png

**Comment by Nitive** [comment]
В итоге решили через внедрение JS скрипта на страницу
